name: dit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - pip:
    - timm
    - diffusers
    - accelerate

